services:
  # 1. Microservicio de Usuarios
  - type: web
    name: usuarios-service
    runtime: docker
    dockerfilePath: usuarios-service/usuarios-service/Dockerfile
    dockerContext: usuarios-service/usuarios-service
    plan: free
    region: oregon

  # 2. Microservicio de Ofertas
  - type: web
    name: ofertas-service
    runtime: docker
    dockerfilePath: ofertas-service/ofertas-service/Dockerfile
    dockerContext: ofertas-service/ofertas-service
    plan: free
    region: oregon

  # 3. Microservicio de Postulaciones
  - type: web
    name: postulaciones-service
    runtime: docker
    dockerfilePath: postulaciones-service/postulaciones-service/Dockerfile
    dockerContext: postulaciones-service/postulaciones-service
    plan: free
    region: oregon

  # 4. Frontend Web (React + Vite SPA)
  - type: web
    name: empleabilidad-frontend
    runtime: static
    rootDir: empleabilidad-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
