spring.application.name=usuarios-service

server.port=${PORT:8081}

# PostgreSQL Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://ep-orange-snow-b599ngwh-pooler.c-7.us-east-2.aws.neon.tech:5432/db_empleapro?sslmode=require&currentSchema=public}
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_xctadB5wTQ0K}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true

# JWT Secret
jwt.secret=${JWT_SECRET:my-super-secret-key-that-should-be-changed-in-production}

storage.local.base-path=${STORAGE_LOCAL_BASE_PATH:${java.io.tmpdir}}
storage.cv.max-size-mb=${STORAGE_CV_MAX_SIZE_MB:5}

# PeruAPI - Configuracion para consultas DNI/RUC
apisperu.token=${APISPERU_TOKEN:adfdc4c3c78621141079079b2e5deb05}
apiperu.token=${APISPERU_TOKEN:adfdc4c3c78621141079079b2e5deb05}
apisperu.dni-url=${APISPERU_DNI_URL:https://peruapi.com/api/dni}
apisperu.ruc-url=${APISPERU_RUC_URL:https://peruapi.com/api/ruc}

# Cargar variables opcionales de .env en la raiz y local
spring.config.import=optional:file:../../.env[.properties],optional:file:./.env[.properties]

